config/routes.rb
FriendCircle::Application.routes.draw do
  resource :session
  resources :users do
    resources :friend_circs, shallow: true do
      resources :friend_circle_memberships, shallow: true 
    end
    
    resources :posts, shallow: true do
      resource :links, shallow: true
    end
    
    collection do
      get 'reset'
    end
  end
end

app/models/friend_circ.rb
class FriendCirc < ActiveRecord::Base
  attr_accessible :name

  belongs_to(
  :owner,
  :class_name => "User",
  :foreign_key => :user_id,
  :primary_key => :id
  )

  has_many(
  :memberships,
  :class_name => "FriendCircleMembership",
  :foreign_key => :friend_circ_id,
  :primary_key => :id
  )
  
  has_many(
  :post_shares,
  :class_name => "PostShare",
  :foreign_key => :friend_circ_id,
  :primary_key => :id
  )
  
  has_many :posts, :through => :post_shares, :source => :post

  has_many :members, :through => :memberships, :source => :owner


end

app/models/friend_circle_membership.rb
class FriendCircleMembership < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :user_id, :friend_circ_id

  belongs_to(
    :owner,
    :class_name => "User",
    :foreign_key => :user_id,
    :primary_key => :id
  )


  belongs_to(
    :circle,
    :class_name => "FriendCirc",
    :foreign_key => :friend_circ_id,
    :primary_key => :id
  )
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url, :post_id
  validates :post, :url, presence: true
  # validates :url, length: { minimum: 1 }
  
  belongs_to(
  :post,
  :class_name => "Post",
  :foreign_key => :post_id,
  :primary_key => :id,
  :inverse_of => :links
  )
  
  # belongs_to(
  # :post,
  # :class_name => "Post",
  # :foreign_key => :post_id,
  # :primary_key => :id
  # )
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :user_id, :body
  
  belongs_to(
  :user,
  :class_name => "User",
  :foreign_key => :user_id,
  :primary_key => :id
  )
  
  has_many(
  :links,
  :class_name => "Link",
  :foreign_key => :post_id,
  :primary_key => :id,
  :inverse_of => :post
  )
  
  has_many(
  :post_shares,
  :class_name => "PostShare",
  :foreign_key => :post_id,
  :primary_key => :id
  )
  
  has_many :friend_circs, :through => :post_shares, :source => :friend_circ
end

app/models/post_share.rb
class PostShare < ActiveRecord::Base
  attr_accessible :friend_circ_id, :post_id
  
  belongs_to(
  :friend_circ,
  :class_name => "FriendCirc",
  :foreign_key => :friend_circ_id,
  :primary_key => :id
  )
  
  belongs_to(
  :post,
  :class_name => "Post",
  :foreign_key => :post_id,
  :primary_key => :id
  )
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :password, :session_token
  validates :email, :password_digest, :session_token, presence: true
  before_validation(on: :create) do
    self.reset_session_token! unless self.session_token
  end

  has_many(
    :circles,
    :class_name => "FriendCirc",
    :foreign_key => :user_id,
    :primary_key => :id
  )

  has_many(
    :memberships,
    :class_name => "FriendCircleMembership",
    :foreign_key => :user_id,
    :primary_key => :id
  )

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    self.save!
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
  end

  def self.find_by_params(email, password)
    user = User.find_by_email(email)
    if user
      return user if user.is_password?(password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/friend_circle_memberships_controller.rb
# require 'debugger'

class FriendCircleMembershipsController < ApplicationController
  def show
    # @circle = FriendCirc.find(params[:friend_circ_id])
    # @users = User.all
    render :show
  end

  def new
    @circle = FriendCirc.find(params[:friend_circ_id])
    # @user = User.find(params[:user_id])
    @users = User.all
    render :new
  end

  def create
    # debugger
    @user = User.find(params[:user_id])
    @circle = FriendCirc.find(params[:friend_circ_id])
    @circle.member_ids = params[:friend_circle_membership][:user_id]
    # @friend = FriendCircleMembership.new({ :user_id => params[:friend_circle_membership][:user_id],
    #                                        :friend_circ_id => @circle.id })


    if @circle.save
      redirect_to user_friend_circ_url(@user, @circle)
    else
      render :json => "Add member error"
    end
  end
end

app/controllers/friend_circs_controller.rb
class FriendCircsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    render :new
  end

  def create
    @friend_circ = FriendCirc.new(params[:friend_circ])
    @friend_circ.user_id = current_user.id

    if @friend_circ.save
      # might need to change so user must be logged in user
      redirect_to user_friend_circs_url(current_user)
    else
      flash.now[:errors] = @friend_circ.errors.full_messages
      render :new
    end
  end

  def show
    # @user = User.find(params[:user_id])
    @friend_circ = FriendCirc.find(params[:id])
    render :show
  end
  
  def index
    @user = User.find(params[:user_id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    render :new
  end
  
  def create
    @post = Post.new({ :body => params[:post][:body]})
    @post.user_id = params[:user_id]
    @post.friend_circ_ids = params[:post][:friend_circ_id]
    
    # params[:link] will return an array of hashes => {:url => "test"}, 
    # params[:link].values will return the individual hashes, not in an array
    @post.links.new(params[:link].values.keep_if { |url_hash| url_hash["url"].length > 0 })
    if @post.save
      render :text => "SUCCESS"
    else
      render :text => "FAIL"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_params(params[:user][:email], params[:user][:password])
    if @user
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:notice] = "Do later"
      render :new
    end
  end

  def destroy
    user = User.find(params[:id])
    user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "whatever"
    else
      redirect_to new_user_url
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def reset
    user = User.find_by_email(params[:user][:email])
    if user
      msg = UserMailer.change_password_email(user)
      print msg
      msg.deliver!
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      render :json => "Logged in"
    else
      flash.now[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end
  
  def show
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_circle_memberships_helper.rb
module FriendCircleMembershipsHelper
end

app/helpers/friend_circs_helper.rb
module FriendCircsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_circle_memberships/new.html.erb
<h3>Add members to <%= @circle.name %></h3>

<form action="<%= friend_circ_friend_circle_memberships_url(@circle) %>" method="post" >

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
<input type="hidden" name="friend_circle_membership[user_id][]" value="">
<% @users.each do |user| %>
<input type="checkbox" name="friend_circle_membership[user_id][]" id="friend_circle_membership#{user.id}" value=<%= user.id %> >
<label for="friend_circle_membership#{user.id}"><%= user.email%></label>
<br>

<% end %>

<input type="submit" value="Add Members">
</form>

app/views/friend_circs/index.html.erb
<!-- <%= link_to("Return to index", )%> -->

<ul>
  <li>Circle ID   Name</li>
  <% @user.circles.each do |circle| %>
  <li><%= circle.id %>&nbsp;&nbsp;&nbsp;<%= link_to("#{circle.name}", friend_circ_url(circle), method: :get) %></li>
  <% end %>
</ul>

<%= button_to("Create Friend Circle", new_user_friend_circ_url, method: :get) %>
<br>
<%= button_to("Create Post", new_user_post_url(@user), method: :get) %>

app/views/friend_circs/new.html.erb
<form action="<%= user_friend_circs_url(@user) %>" method="post">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

  <label for="friend_circ_name">Name:</label>
  <input type="text" name="friend_circ[name]" value="" id="friend_circ_name">

  <input type="submit" value="Create Friend Circ">

</form>

app/views/friend_circs/show.html.erb
<h3><%= @friend_circ.name %></h3>
<ul>
  <% @friend_circ.members.each do |member| %>
  <li><%= member.email %></li>
  <% end %>
</ul>
<br>

<%= button_to("Add members", new_friend_circ_friend_circle_membership_url(@friend_circ), method: :get) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FriendCircle</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if logged_in? %>
  <%= current_user.email %>
  <%= button_to("Sign Out", session_url, method: :delete) %>
  <% else %>
  <%= button_to("Sign In", new_session_url, method: :get) %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<h2>Create New Post</h2>
<form action="<%= user_posts_url(@user) %>" method="post">
  
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

  <label for="post[body]">Body:</label>
  <input type="text" name="post[body]" value="" id="post_body">
  <br>
  <br>
  
  <h4>Post To:</h4>
  <% @user.circles.each do |circle| %>
  <label for="post_friend_circ_id"><%= circle.name %></label>
  <input type="checkbox" name="post[friend_circ_id][]" value=<%= circle.id %> id=<%= "post_circle_#{circle.id}" %>>
  <br>
  <% end %>
  <br>
  
  <input type="hidden" name="link[1][url]" value="">
  <input type="hidden" name="link[2][url]" value="">
  <input type="hidden" name="link[3][url]" value="">
  <label for="link_url_1">URL:</label>
  <input type="text" name="link[1][url]" id="link_url_1">
  <!-- <input type="text" name="link[url][]" id="link_url_1"> -->
  <br>
  
  <label for="link_url_2">URL:</label>
  <input type="text" name="link[2][url]" id="link_url_2">
  <!-- <input type="text" name="link[url][]" id="link_url_2"> -->
  <br>
  
  <label for="link_url_3">URL:</label>
  <input type="text" name="link[3][url]" id="link_url_3">
  <!-- <input type="text" name="link[url][]" id="link_url_3"> -->
  <br>
  <br>
  
  <input type="submit" value="Create Post">

</form>

app/views/users/edit.html.erb
<form action="<%= user_url %>" method="post">
  <input type="hidden" name ="_method" value="put">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

  <label for="user_email">Email:</label>
  <input type="text" name="user[email]" value="<%= @user.email %>" id="user_email">
  <label for="user_password">Password:</label>

  <input type="password" name="user[password]" value="" id="user_password">

  <br />
  <input type="submit" value="Reset Password">

</form>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="post">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

  <label for="user_email">Email:</label>
  <input type="text" name="user[email]" value="" id="user_email">
  <label for="user_password">Password:</label>
  <input type="password" name="user[password]" value="" id="user_password">

  <br />
  <input type="submit" value="Sign Up">

</form>
<br>

<form action="<%= reset_users_url %>" method="get">

  <label for="user_email">Email:</label>
  <input type="text" name="user[email]" value="" id="user_email">

  <br />
  <input type="submit" value="Reset Password">

</form>